### ISSUE TITLE
Problems decoding gziped sitemaps

### ISSUE THREAD

**Issue by ThatIsGeek** [tzfrs/googlesitemapparser#6]
When I tried parsing gziped sitemap I ran in to problem with generator just returning gibberish. It turns out that the function downloadAndExtractGZIP does not actually "extract gzip".  I have the change ready in my fork but it will break examples and possibly other peoples code. Maybe we could figure out some smarter way to distinguish xml from xml.gz then file extension?

**Comment by kobelobster** [comment]
You are right. I don't know why I didn't implement this stuff. Since this is an older project of mine when I was only one year programming, I could create a "new" version and tag is at 2.0. 2.0 shouldn't break peoples code if they are using versions for requiring this library. What do you think about that?

**Comment by ThatIsGeek** [comment]
Sounds great!
