### ISSUE TITLE
Allow setting custom HTTP headers

### ISSUE THREAD

**Issue by ThatIsGeek** [tzfrs/googlesitemapparser#7]
I ran into site which allows access to sitemap only to some User-Agents.
It would be nice to have the ability to set custom HTTP headers.

**Comment by JanPetterMG** [comment]
Just discovered this project, and custom HTTP headers is an must-have requirement.
It seems easy to implement, so when I get the time, (probably a day or two), I'll do the required changes and submitting the PR. Stay tuned!

**Comment by kobelobster** [comment]
Thanks for opening this issue. I will add this functionality in the next few hours.

**Comment by kobelobster** [comment]
I just looked through the code, and that will be more work than I thought that it would be, because i'm not using a function for making the requests, but am making them individually in every method. 

As I mentioned here https://github.com/tzfrs/googlesitemapparser/issues/6 since my coding standards have changed over the past 10 months, I would create a "new" version and tag it as 2.0.

What do you think?

**Comment by JanPetterMG** [comment]
Sounds great.
btw. I'll just updated my fork with an fix for this issue (untested atm), and it probably won't break any backwards compatibility as far as I know atm.
